### ISSUE TITLE
Inheritance graph linearization

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/surya#1]
Federico has something for this too: https://www.npmjs.com/search?q=c3%20linearize

It would be nice to be able to linearize something like this: 

![acl2](https://user-images.githubusercontent.com/23033765/39249140-f50d2828-486b-11e8-81b8-8c4ffb7b1b54.png)

**Comment by GNSPS** [comment]
Would a queriable list of linearized dependencies be enough? Just because I don't see much merit in displaying the linearized dependency list of every contract in a graph

**Comment by maurelian** [comment]
ie, I can specify a contract, and get the linearization of it's parents? 

Yes, that's useful.
