### ISSUE TITLE
How to use surya to output inheritance among all contracts which exits different hierarchy?

### ISSUE THREAD

**Issue by YukinoriHamada** [ConsenSys/surya#111]
For example, I want to know ERC1400(https://github.com/ConsenSys/ERC1400) inheritance to use surya.

All I can do is here.
```
ERC1400-master $ surya inheritance contracts/*.sol | dot -Tpng > erc1400-inheritance.png
```
this shows parts of ERC1400 inheritance.I also want to know mock directory, token directory!

Has anyone good ideas?

**Comment by GNSPS** [comment]
I'd suggest to start by trying the following command:

```
$ surya inheritance contracts/**/*.sol | dot -Tpng > erc1400-inheritance.png
```

But, in case you have VSCode installed, there is an amazing extension that helps you map out all the call and inheritance graphs of the whole project or a specific group of files.

It's called "Solidity Visual Auditor" and can be found here: https://marketplace.visualstudio.com/items?itemName=tintinweb.solidity-visual-auditor

Here is a good preview of this capability:

![](https://user-images.githubusercontent.com/2865694/57710279-e27e8a00-766c-11e9-9ca9-8cde50aa31fc.gif)
