### ISSUE TITLE
ftrace: `opts` and `colorScheme` are not defined

### ISSUE THREAD

**Issue by hacker-DOM** [ConsenSys/surya#134]
On this line [[1]](https://github.com/ConsenSys/surya/blob/9dccd092e3d2423baadfbb70aa420d0ba09b2070/src/ftrace.js#L410), both `opts` and `colorScheme` are not defined. This results in nothing happening when the function is called, e.g. from [vscode-solidity-auditor](https://github.com/ConsenSys/vscode-solidity-auditor/issues/44).

**Comment by GNSPS** [comment]
Thank you @hacker-DOM! Merged and closed
