### ISSUE TITLE
The describe command mishandles the `receive()` function

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/surya#155]
**What I did:**
Ran `surya describe` on this [contract](https://etherscan.io/address/0xe468ce99444174bd3bbbed09209577d25d1ad673#code#F1#L1)

I got this output: 

```
 +  AuctionHouse (IAuctionHouse, ReentrancyGuard)
... skipped output ...
    - [Ext] <Fallback> ($)
    - [Ext] <Fallback> ($)
```

**Version:**
```
surya --version
0.4.3-dev.2
```

**Possible fix**

Pretty sure this:
https://github.com/ConsenSys/surya/blob/4340e703434e4314e778f558675c70d821714cf0/src/describe.js#L85-L86

Just needs to look more like this: 

https://github.com/ConsenSys/surya/blob/4340e703434e4314e778f558675c70d821714cf0/src/graph.js#L200-L203

**Comment by GNSPS** [comment]
Thank you! ❤️
