### ISSUE TITLE
Surya cannot parse new error format as of 0.8.4

### ISSUE THREAD

**Issue by KeeganBlack** [ConsenSys/surya#160]
In Solidity 0.8.4, a new way of erroring with a custom message was added. 

https://blog.soliditylang.org/2021/04/21/custom-errors/

Surya is unable to parse any contract that uses this new kind of error handling. You get a mismatched input error, for example: 

errors: [
    {
      message: "mismatched input '(' expecting {';', '='}",
      line: 49,
      column: 30
    }
  ]

**Comment by GNSPS** [comment]
Thanks @KeeganBlack ! I'll get the parser updated!

**Comment by GNSPS** [comment]
The parser actually wasn't pinned for a long time, you only needed to uninstall and install surya whenever this happens, sorry for not getting back to you, sooner! :🙈
