### ISSUE TITLE
I love this project! and have a suggestion

### ISSUE THREAD

**Issue by LuozhuZhang** [ConsenSys/surya#166]
According to my current use, surya can only export the relationship between contract calls

Nevertheless, this feature is already very useful

But I found another requirement when reading the contract source code:

Like the [zkSync v1 contract source code](https://github.com/LuozhuZhang/sourceCode-zkSync-rollupContract), I'm looking to find the entry file when I read it, so maybe surya can do a graph between the import files and export files

This way I can clearly see which solidity file is the base file and which solidity file calls other files. Very useful for reading source code

Just like this 👇

![WechatIMG17369](https://user-images.githubusercontent.com/70309026/166097330-1637a719-7408-4601-9531-0af620226432.jpeg)

**Comment by GNSPS** [comment]
Hey @LuozhuZhang! 😊 👋 

We do have the inheritance graph command that already presents you with the inheritance order. Is this something that fits your needs or were you looking for something else?
