### ISSUE TITLE
Generating the graph with type casting address(...) as a function.

### ISSUE THREAD

**Issue by tintinweb** [Consensys/surya#186]
see original: https://github.com/Consensys/vscode-solidity-auditor/issues/134

> When generating a call graph, the extensions sees typecasting like `address(this)` or `address(some contract/interface)` as a function and this is not only incorrect, but also visually clutters the chart. See example: 
![image](https://github.com/Consensys/vscode-solidity-auditor/assets/96236521/d7f7f8cb-b243-4abe-9cdc-010538bbe1ea)
I think the fix should be pretty easy on this, just adding logic to ignore a function if it's name is `address` since that's impossible anyway in Solidity because the term is reserved for the type.

**Comment by GNSPS** [comment]
Taking a look

**Comment by GNSPS** [comment]
90% fixed in PR #187. Not closing because there's 10% to go. 🙈

**Comment by GNSPS** [comment]
Closing because I realised the extra 10% need a major refactoring.
