### ISSUE TITLE
Support running on Truffle projects contract folder

### ISSUE THREAD

**Issue by GNSPS** [ConsenSys/surya#24]
Implement a global flag, accepted on every command, that runs the command on every contract inside Truffle's contract folder (if ran from the root folder).

The point is to avoid the whole `find contracts -name "*.sol" -print | xargs surya [sub-command]` pattern and substitute it for `surya -t [sub-command]`

**Comment by maurelian** [comment]
Pretty sure this is unnecessary since globs work?

**Comment by GNSPS** [comment]
Yep! Thank you for noticing that! 😄 

Also worth it to change the `Usage Tips` section in the README file since I had never tried using globs before!
