### ISSUE TITLE
[EPIC] Generate a complete summary of a contract

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/surya#26]
This is a bit of an epic, but the more I use surya, the more I want this. 

I want to generate a summary of the resulting child contract after inheritance, including storage, and all functions.

The output would be something like this: 

```
Exchange

    address public currentContextAddress;
    mapping (bytes4 => IAssetProxy) public assetProxies;
    mapping (bytes32 => mapping (address => bool)) public preSigned;
   ...

    MixinWrapperFunctions::fillOrKillOrder() public
    MixinAssets::withdrawERC20() external
...

   etc.
```

But prettier. This feature would combine elements of `ftrace` and `dependencies`, and require new storage parsing, but it would be awesome.

**Comment by maurelian** [comment]
^ I hit enter too soon, still editing.

**Comment by maurelian** [comment]
ok, done now. ^^

**Comment by GNSPS** [comment]
I like this! Do you think it requires more storage parsing than `ftrace`, though? I feel that we could make do with the current auxiliary parsing methods.

**Comment by maurelian** [comment]
I'm looking at `ftrace` now, and yes, it seems like the parsing in there should be sufficient to repurpose for this use case.

**Comment by maurelian** [comment]
Includes: 
[ ] #33 
[ ] #37
[ ] #38
