### ISSUE TITLE
Improvements to the `dependencies` command

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/surya#28]
From @federicobond on twitter:

> Would be awesome to show the inheritance subgraph for every method (showing only those parent contracts where the overridden method is defined). Also distinguish overridden completely vs extended using super.

I agree, as identifying function overrides is the real motivation for this feature. Maybe that would look like 

```
Child
  ↖ Parent1
      - foo() overrides Parent2::foo()
  ↖ Parent2
      - foo() overridden
      - bar() extends Parent3:bar()
  ↖ Parent3
      - bar() extended by Parent2
  ↖ Parent4
  ↖ Parent5
```

Unless developers are doing some really crazy stuff with function overriding, there shouldn't be too much additional output to parse mentally.

**Comment by GNSPS** [comment]
Per a talk we had offline I think this probably belongs in a new, different command.
