### ISSUE TITLE
ftrace mislabels the inherited source contract of called functions

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/surya#30]
![image](https://user-images.githubusercontent.com/23033765/44043855-dcad2e4a-9ef1-11e8-8513-c7eca8aaa6e4.png)

This was generated with `surya ftrace MixinExchangeCore::fillOrder all protocol/Exchange/*.sol` from within this directory: 
https://github.com/0xProject/0x-monorepo/tree/development/packages/contracts/src/2.0.0

All functions in the output are labelled as `MixinExchangeCore`, although many of the called functions are defined in other Mixins. 

**What I know**

For debugging, I focused on the `isValidSiganture` function, which is called [here in `MixinExchangeCore`](https://github.com/0xProject/0x-monorepo/blob/development/packages/contracts/src/2.0.0/protocol/Exchange/MixinExchangeCore.sol#L312), and defined in [MixinSignatureValidator](https://github.com/0xProject/0x-monorepo/blob/development/packages/contracts/src/2.0.0/protocol/Exchange/MixinSignatureValidator.sol#L85). 

I would expect it `parserHelpers.isRegularFunctionCall(node)` to return `true` on it, but none of the `if/else` cases in the FunctionDefinition visitor are matched. If I add `console.log('do nothing block', contractName, functionName)` to the final `else`, there are quite a few functions printed to the log. https://github.com/ConsenSys/surya/blob/master/src/ftrace.js#L247

**Comment by GNSPS** [comment]
I see what's the problem.

`ftrace` makes this wrong assumption: "if the call is a regular function call (as opposed to a member access) then the contract it was defined in was the contract we're looking at".

We can solve the problem of correctly labeling inherited functions by keeping a mapping of `contract -> functions`.

This should be too hard to do.

**Comment by GNSPS** [comment]
I think `ftrace` might just be phased out. Visual Auditor's extension does the job good with selection of node's paths.
