### ISSUE TITLE
 Print legends

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/surya#4]
## context

I'd like to make the tool output very expressive.

ie. for each function in a contract, you should be able to see it's properties for visibility, payability, and mutability.  

This would ideally be done with colors, and expressive symbols. 

## Suggestion

for the `describe`, `graph`, and `inheritance` commands, add a `--legend` option, which would output some simple example contract to demonstrate the meaning of all the colors and symbols.

**Comment by GNSPS** [comment]
Maybe a legend square on top would suffice?
Also the GraphViz engine is not very powerful when it comes to elements/text laid out inside nodes but we'll figure something out.

**Comment by GNSPS** [comment]
Fixed with #13. Closing
