### ISSUE TITLE
Option to remove text output coloring

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/surya#55]
This would simplify copying and sharing output. Eslint uses `--no-color` for this.

**Comment by chronaeon** [comment]
This would be a useful option because the color encoding messes up the appearance of the output when `surya describe` is piped into plaintext using `>`.

**Comment by GNSPS** [comment]
This doesn't seem urgent. Maybe set a milestone for after the refactoring of the codebase?

**Comment by maurelian** [comment]
Yeah, super low pri.

**Comment by GNSPS** [comment]
This is addressed now with a `--no-color` flag in the CLI, and a parameter in all the modules exported that use color. 🎉
