### ISSUE TITLE
Improvement: describe output could be self-explanatory 

### ISSUE THREAD

**Issue by alcuadrado** [ConsenSys/surya#57]
Hi, I want to propose a little improvement. 

I never remember what `surya describe`'s `#` and `($)` mean, so I have to open this repo every time I use `surya`.  

Adding a small explanation in the output would be helpful. Alternatively, the symbols can be replaced with words.

**Comment by GNSPS** [comment]
Hey @alcuadrado! 👋  You're totally right! 😄 

Would emoji characters make it any better? Like 💵 & 🛑 ? Or do you think words would be a better experience?

**Comment by alcuadrado** [comment]
I think the payable one can be pretty evident with `$` or `💵`, but the non-constant one is more confusing. Specially the relationship between them, as `$` implies `#`.

I like that the output is concise, and using words for everything may be too much text. What about adding something like this at the end?

```
$ = payable, non-constant function
# = non-constant function
```

Using emojis is cool, but not widely supported, so take into account that adding them requires some kind of platform detection.
