### ISSUE TITLE
Include option to exclude test / default directories

### ISSUE THREAD

**Issue by chronaeon** [ConsenSys/surya#61]
Files and directories that should (usually) be excluded by default. Consider adding a switch to include these in Surya's analysis if desired.

*Files*
`Migrations.sol`
`Test___.sol`
`test___.sol`

*Directories*
`Tests`
`Test`
`tests`
`test`
`Mocks`
`Mock`
`mocks`
`mock`

**Comment by GNSPS** [comment]
Agree. 😄 

This should be a global option, something like `--truffle-filter, -tf`. We're now refactoring the inner workings of the tool and this will be much easier to implement after we merge the new structure. 

I'm gonna queue this up for after the full "profilers" migration but track it to make sure it happens.

**Comment by chronaeon** [comment]
Partial solution is to use a bash function to filter the file list down.

Put the following code into your bash environment:

```bash
filterFind() { 
    find $rootDir -name "*.sol" | \
    grep -v test* | \
    grep -v Migration* | \
    grep -v mock* | \
    grep -v Mock* | \
    grep -v Test* | \
    grep -v 0x | \
    grep -v Kyber* | \
    grep -v Bytes32.sol | \
    grep -v Authorizable.sol | \
    grep -v AddressArrayUtils.sol | \
    grep -v CommonMath.sol | \
    grep -v node_modules | \
    grep -v coverageEnv  | \
    grep -v openzeppelin-solidity
}
```

Then update the $rootDir variable:
```bash
rootDir=$(/home/someUser/someDir/contracts/)
```
Now your function `filterFind` works on all the files in your contracts directory.

give its output to a new variable:
```bash
filteredDirs=$(filterFind)
```

Lastly, call the variable into Surya:
```bash
surya describe $filteredDirs
```
and your Surya description only prints out the dirs you want it to describe.
