### ISSUE TITLE
[Windows] No such file or directory

### ISSUE THREAD

**Issue by sneko** [ConsenSys/surya#65]
Hi,

I'm trying the following command on Windows:
`surya describe *.sol`

But I get this error:
`Error: ENOENT: no such file or directory, open 'XXXXXXXX\*.sol'`

It seems that the wildcard is not recognized on Windows and that it tries to find a file named `*.sol`.

EDIT: 
I also try giving to the command a directory but I get `Error: EISDIR: illegal operation on a directory, read`.

**Comment by GNSPS** [comment]
It probably depends on where you're running the commands. I don't have a windows machine to test this but I know that the default Windows command line doesn't expand globstar operators.

Also I found this: https://superuser.com/questions/460598/is-there-any-way-to-get-the-windows-cmd-shell-to-expand-wildcard-paths

So maybe you could use PowerShell?

**Comment by sneko** [comment]
@GNSPS I'm already using PowerShell.

The following command is working:
`surya graph contracts/MetaCoin.sol`

But not those:
`surya graph contracts/*`
`surya graph contracts/*.sol`

I understand that's annoying to handle Windows "misconceptions" inside the library, but maybe you could leave the possibility to target a directory? Like that:
`surya graph contracts`

**Comment by maurelian** [comment]
This seems like a good idea. Solium uses `-f` and `-d` flags to distinguish input between files or dirs.
