### ISSUE TITLE
Assignment in place of comparison

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/surya#66]
This should be `==` right?
https://github.com/ConsenSys/surya/blob/39ffdd391176e2cf80b0fe8b3bdd10e966b4e8d2/src/graph.js#L55

And if so could also be `!=` instead of wrapping it with `!()`. 

I didn't see a difference in the output when I changed it, but it doesn't make sense otherwise.

**Comment by smarx** [comment]
I suspect the code is correct as-is. It's the equivalent of:

```javascript
cluster = digraph.getCluster(...); // try to retrieve the cluster
if (!cluster) {
    // if the cluster doesn't already exist, add it
    cluster = digraph.addCluster(...);
    ...
} else {
    // if the cluster already exists, modify it
    ...
}
```

**Comment by GNSPS** [comment]
Yes, it’s meant to be that way, just immediately checking the boolean value of the initialization, inline.

**Comment by maurelian** [comment]
Ahh, I see.
