### ISSUE TITLE
Graphviz interpreter fails on syntax error?

### ISSUE THREAD

**Issue by chronaeon** [ConsenSys/surya#76]
this line is typical of other lines in graphviz generated files that begin with `subgraph`,

```graphviz
subgraph "cluster[{"type":"MemberAccess","expression":{"type":"Identifier","name":"pending"},"memberName":"to"}]"
```
except that the naming convention isn't maintained.

instead of:

```
subgraph "clusterArrays" {
graph [...]
}

subgraph "clusterAddress" {
graph [...]
}

subgraph "clusterReentrancyGuard" {
graph [...]
}
```

we have

```
subgraph "cluster[{"type":"MemberAccess","expression":{"type":"Identifier","name":"pending"},"memberName":"to"}]" {
graph [...]
}
```

so it violates the observed naming convention in this autogenerated file, which returns a syntax error when run through `dot -Tpng`

**Comment by guylando** [comment]
why is this closed if it still does not work?

**Comment by GNSPS** [comment]
Has this happened to you in the latest version, @guylando? 

Could you please point me to a code example where I could reproduce this crash?

**Comment by guylando** [comment]
@GNSPS 
just running 
npm install -g surya
surya inheritance MyContract.sol
produces exactly the problem described here

**Comment by GNSPS** [comment]
But do you happen to have the source for "MyContract.sol"? 😊 

If you call it with an inexistent file as a parameter it should error out automatically and not output any Graphviz DAG.

**Comment by guylando** [comment]
https://github.com/guylando/EthereumSmartContracts/blob/master/SafeUpgradeableTokenERC20/contracts/SafeUpgradeableTokenERC20.sol

"If you call it with an inexistent file as a parameter it should error out automatically and not output any Graphviz DAG.", oh really?! surprising!

**Comment by GNSPS** [comment]
So the "MyContract.sol" is actually a placeholder for the name of the contract whose inheritance you want to graph!

Surya is actually working with your example contract. What I did:
`$ git clone git@github.com:guylando/EthereumSmartContracts.git`
`$ cd SafeUpgradeableTokenERC20/contracts`
`$ surya inheritance SafeUpgradeableTokenERC20.sol`

And it outputs a Graphviz valid file.

There are other options to run Surya on your codebase, though. Some examples are:

`$ surya inheritance contracts/**/*.sol` <- calling it with a glob pattern will pass along a list of files to be fed to Surya that will all be processed together
`$ surya inheritance -i SafeUpgradeableTokenERC20.sol` <- using the `-i` (or `--importer`) flag actually fetches all the files that are imported in the files passed along automatically

**Comment by GNSPS** [comment]
This being said I don't think there actually is a bug here! 😄
