### ISSUE TITLE
ftrace address.transfer()/address.send() Error

### ISSUE THREAD

**Issue by rmi7** [ConsenSys/surya#9]
the `address.transfer()` and `address.send()` builtin solidity functions seem to be not recognized by the `ftrace` command.

## Contract

```javascript
pragma solidity ^0.4.18;

contract Test {
  function _transfer(address _to, uint256 _amount) public {
    _to.transfer(_amount);
  }
  function _send(address _to, uint256 _amount) public {
    _to.send(_amount);
  }
  function _call_value(address _to, uint256 _amount) public {
    _to.call.value(_amount)();
  }
}
```

## Actual result
running `surya ftrace` on this file gives

| command | output errors |
|--|--|
| `surya Test::_transfer all Test.sol` | `TypeError: Cannot read property 'transfer' of undefined` |
| `surya Test::_send all Test.sol` | `TypeError: Cannot read property 'send' of undefined` |
| `surya Test::_call_value all Test.sol` | no errors |

error output stack trace is in both cases:

```
at constructCallTree (/usr/local/lib/node_modules/surya/lib/ftrace.js:397:49)
at /usr/local/lib/node_modules/surya/lib/ftrace.js:441:11
at Array.forEach (<anonymous>)
at constructCallTree (/usr/local/lib/node_modules/surya/lib/ftrace.js:428:34)
at ftrace (/usr/local/lib/node_modules/surya/lib/ftrace.js:450:3)
```

## Expected result
No errors output

**Comment by GNSPS** [comment]
Totally right! I'm on it Alexander. Thanks! 😄

**Comment by rmi7** [comment]
I noticed that if there is a `using SafeMath for uint`, the `div`/`add`/etc. are also not recognized.

FYI included surya tool into `solhydra`: https://github.com/BlockChainCompany/solhydra/releases/tag/v1.0.0
also a great way to check for `surya` errors, run it on a big project and watch the console for errors

**Comment by GNSPS** [comment]
That is actually known (and tracked on #6) but a feature not as easy to implement right now! 😄 

This issue was fixed with my latest commits so I'll close it now.
