### ISSUE TITLE
Old constructor pattern (same name as the contract) does not render correctly in "graph"

### ISSUE THREAD

**Issue by GNSPS** [ConsenSys/surya#97]
If an old version of the Solidity compiler was used and the constructor still uses the syntax pattern where it has the same name as the contract it is in, the `graph` command renders it as a different node outside of the contract cluster.

**Comment by maurelian** [comment]
I came here to report this. 

Running surya graph on this codebase is a good way to repro:

https://github.com/ConsenSys/panvala/blob/d65744451d3aa22c3dc2a91cd27241494a4f94d5/governance-contracts/contracts/TokenCapacitor.sol#L79

![image](https://user-images.githubusercontent.com/23033765/61906955-746f0280-aefa-11e9-984d-48666b5173b7.png)

**Comment by GNSPS** [comment]
This is done in 0.3.x

Closing!
